// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kin",
            "email": "trannguyentrungkien1006@gmail.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admins": {
            "get": {
                "description": "Lấy danh sách admin với phân trang, lọc, sắp xếp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get admin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trang",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng/trang",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trường sắp xếp",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Thứ tự sắp xếp (ASC/DESC)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trường lọc (vd: email, full_name)",
                        "name": "searchBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Giá trị lọc (vd:abc@gmail.com, John Doe)",
                        "name": "searchValue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admindto.GetAdminResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "put": {
                "description": "Cập nhật thông tin admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update admin",
                "parameters": [
                    {
                        "description": "Thông tin cập nhật",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admindto.UpdateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admindto.UpdateAdminResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "post": {
                "description": "Tạo mới admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create admin",
                "parameters": [
                    {
                        "description": "Thông tin admin",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admindto.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/admindto.CreateAdminResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/admins/{adminID}": {
            "get": {
                "description": "Lấy chi tiết admin theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get admin by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Admin ID",
                        "name": "adminID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admindto.GetAdminByIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Xóa admin theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete admin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Admin ID",
                        "name": "adminID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admindto.UpdateAdminResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/items": {
            "get": {
                "description": "API bao gồm cả lọc, phân trang và sắp xếp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get items",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 1,
                        "description": "Current page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "description": "Number record per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "name",
                        "description": "Sort column (vd: name)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "ASC",
                        "description": "Sort type: ASC hoặc DESC",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trường lọc (vd: email, full_name)",
                        "name": "searchBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Giá trị lọc (vd:abc@gmail.com, John Doe)",
                        "name": "searchValue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/itemdto.GetItemResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "put": {
                "description": "API cập nhật item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Update item",
                "parameters": [
                    {
                        "description": "Update item info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/itemdto.UpdateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated item successfully",
                        "schema": {
                            "$ref": "#/definitions/itemdto.UpdateItemResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "post": {
                "description": "API thêm item mới",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Create new item",
                "parameters": [
                    {
                        "description": "Create item info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/itemdto.CreateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created item successfully",
                        "schema": {
                            "$ref": "#/definitions/itemdto.CreateItemResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/items/{itemID}": {
            "get": {
                "description": "API lấy thông tin item theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get item by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID item",
                        "name": "itemID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/itemdto.GetItemByIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "delete": {
                "description": "API xóa item theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Delete item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID item",
                        "name": "itemID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deleted item successfully",
                        "schema": {
                            "$ref": "#/definitions/itemdto.DeleteItemResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/request-sends": {
            "post": {
                "description": "API gửi yêu cầu gửi đồ cũ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Create request to send old item",
                "parameters": [
                    {
                        "description": "Create request send old item",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requestdto.CreateRequestSendOldItem"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created request successfully",
                        "schema": {
                            "$ref": "#/definitions/requestdto.CreateSendOldItemRequestResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "API bao gồm cả lọc, phân trang và sắp xếp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get users",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 1,
                        "description": "Current page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "description": "Number record of page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "name",
                        "description": "Sort column (vd: fullName, email)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "ASC",
                        "description": "Sort type: ASC hoặc DESC",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trường lọc (vd: email, fullName)",
                        "name": "searchBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Giá trị lọc (vd:abc@gmail.com, John Doe)",
                        "name": "searchValue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userDTO.GetUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "put": {
                "description": "API cập nhật người dùng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "description": "Update user info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDTO.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user successfully",
                        "schema": {
                            "$ref": "#/definitions/userDTO.UpdateUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "post": {
                "description": "API thêm người dùng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "Create user info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDTO.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created user successfully",
                        "schema": {
                            "$ref": "#/definitions/userDTO.CreateUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/users/{userID}": {
            "get": {
                "description": "API get user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID user",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userDTO.GetUserByIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "delete": {
                "description": "API delete user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID user",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userDTO.DeleteUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admindto.AdminDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "roleName": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "admindto.CreateAdminRequest": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password",
                "roleId"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@gmail.com"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "roleId": {
                    "description": "Role ID must be provided, e.g., 1 for Admin, 2 for Moderator",
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "description": "0: Inactive, 1: Active, 2: Suspended",
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.UserStatus"
                        }
                    ],
                    "example": 0
                }
            }
        },
        "admindto.CreateAdminResponse": {
            "type": "object",
            "properties": {
                "admin": {
                    "$ref": "#/definitions/admindto.AdminDTO"
                }
            }
        },
        "admindto.CreateAdminResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/admindto.CreateAdminResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "admindto.GetAdminByIDResponse": {
            "type": "object",
            "properties": {
                "admin": {
                    "$ref": "#/definitions/admindto.AdminDTO"
                }
            }
        },
        "admindto.GetAdminByIDResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/admindto.GetAdminByIDResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "admindto.GetAdminResponse": {
            "type": "object",
            "properties": {
                "admins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admindto.AdminDTO"
                    }
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "admindto.GetAdminResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/admindto.GetAdminResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "admindto.UpdateAdminRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "id": {
                    "type": "integer"
                },
                "roleId": {
                    "description": "Role ID must be provided, e.g., 1 for Admin, 2 for Moderator",
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "description": "0: Inactive, 1: Active, 2: Suspended",
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.UserStatus"
                        }
                    ],
                    "example": 0
                }
            }
        },
        "admindto.UpdateAdminResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "enums.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "type": "string",
                    "example": "INVALID_QUERY_PARAM"
                },
                "message": {
                    "type": "string",
                    "example": "Name is require"
                }
            }
        },
        "enums.RequestStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-comments": {
                "RequestStatusApprove": "3 Người dùng đồng ý",
                "RequestStatusFail": "4 Người dùng đã hủy",
                "RequestStatusPending": "0 Người dùng đã gửi yêu cầu và đang chờ xử lý",
                "RequestStatusReject": "2 Admin đã từ chối yêu cầu",
                "RequestStatusWaitingUser": "1 Admin đã xác nhận và đang chờ người dùng xác nhận lần cuối"
            },
            "x-enum-varnames": [
                "RequestStatusPending",
                "RequestStatusWaitingUser",
                "RequestStatusReject",
                "RequestStatusApprove",
                "RequestStatusFail"
            ]
        },
        "enums.RequestType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "RequestTypeReceiveLoseItem": "3",
                "RequestTypeReceiveOldItem": "2",
                "RequestTypeSendLoseItem": "1",
                "RequestTypeSendOldItem": "0"
            },
            "x-enum-varnames": [
                "RequestTypeSendOldItem",
                "RequestTypeSendLoseItem",
                "RequestTypeReceiveOldItem",
                "RequestTypeReceiveLoseItem"
            ]
        },
        "enums.UserStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "UserStatusActive": "1",
                "UserStatusInactive": "0",
                "UserStatusLocked": "2"
            },
            "x-enum-varnames": [
                "UserStatusInactive",
                "UserStatusActive",
                "UserStatusLocked"
            ]
        },
        "itemdto.CreateItemRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "itemdto.CreateItemResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/itemdto.ItemDTO"
                }
            }
        },
        "itemdto.CreateItemResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/itemdto.CreateItemResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "itemdto.DeleteItemResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "itemdto.GetItemByIDResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/itemdto.ItemDTO"
                }
            }
        },
        "itemdto.GetItemByIDResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/itemdto.GetItemByIDResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "itemdto.GetItemResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/itemdto.ItemDTO"
                    }
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "itemdto.GetItemResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/itemdto.GetItemResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "itemdto.ItemDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "itemdto.UpdateItemRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "itemdto.UpdateItemResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/itemdto.ItemDTO"
                }
            }
        },
        "itemdto.UpdateItemResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/itemdto.UpdateItemResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "requestdto.CreateRequestSendOldItem": {
            "type": "object",
            "required": [
                "appointmentLocation",
                "appointmentTime"
            ],
            "properties": {
                "appointmentLocation": {
                    "description": "Location of the appointment",
                    "type": "string",
                    "example": "123 Main St, City, Country"
                },
                "appointmentTime": {
                    "description": "Time in RFC3339 format",
                    "type": "string",
                    "example": "2025-05-28T07:23:45Z"
                },
                "description": {
                    "type": "string",
                    "example": "I want to send this old item to the charity organization."
                },
                "email": {
                    "type": "string",
                    "example": "john@gmail.com"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "isAnonymous": {
                    "description": "true: anonymous, false: not anonymous",
                    "type": "boolean"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "0123456789"
                },
                "type": {
                    "description": "1: Send Old Item, 2: Request Item, 3: Request Post, 4: Reply Post",
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.RequestType"
                        }
                    ],
                    "example": 0
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "requestdto.CreateSendOldItemRequestResponse": {
            "type": "object",
            "properties": {
                "request": {
                    "$ref": "#/definitions/requestdto.RequestSendOldItem"
                }
            }
        },
        "requestdto.CreateSendOldItemRequestResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/requestdto.CreateSendOldItemRequestResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "requestdto.RequestSendOldItem": {
            "type": "object",
            "properties": {
                "appointmentLocation": {
                    "description": "Location of the appointment",
                    "type": "string"
                },
                "appointmentTime": {
                    "description": "Time in RFC3339 format",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isAnonymous": {
                    "type": "boolean"
                },
                "replyMessage": {
                    "description": "Optional, used for replies",
                    "type": "string"
                },
                "status": {
                    "description": "0: Pending, 1: Accepted, 2: Rejected, 3: Completed",
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.RequestStatus"
                        }
                    ]
                },
                "type": {
                    "description": "1: Send Old Item, 2: Request Item, 3: Request Post, 4: Reply Post",
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.RequestType"
                        }
                    ]
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "userDTO.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "john@gmail.com"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "goodPoint": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "0123456789"
                },
                "status": {
                    "description": "0: inactive, 1: active, 2: banned",
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.UserStatus"
                        }
                    ],
                    "example": 1
                }
            }
        },
        "userDTO.CreateUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/userDTO.UserDTO"
                }
            }
        },
        "userDTO.CreateUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/userDTO.CreateUserResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "userDTO.DeleteUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "userDTO.GetUserByIDResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/userDTO.UserDTO"
                }
            }
        },
        "userDTO.GetUserByIDResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/userDTO.GetUserByIDResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "userDTO.GetUserResponse": {
            "type": "object",
            "properties": {
                "totalPage": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userDTO.UserDTO"
                    }
                }
            }
        },
        "userDTO.GetUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/userDTO.GetUserResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "userDTO.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "goodPoint": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "major": {
                    "type": "string",
                    "example": "Information Technology"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "0123456789"
                },
                "status": {
                    "description": "0: inactive, 1: active, 2: banned",
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.UserStatus"
                        }
                    ],
                    "example": 1
                }
            }
        },
        "userDTO.UpdateUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "userDTO.UserDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "goodPoint": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "major": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "34.142.168.171:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API DATN 2025",
	Description:      "Đây là tài liệu Swagger cho hệ thống.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
