// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kin",
            "email": "trannguyentrungkien1006@gmail.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "API lấy ra tất cả danh mục đồ đạc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/categorydto.GetCategoryResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/import-invoice": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "API tạo phiếu nhập kho kèm lưu kho",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "import invoice"
                ],
                "summary": "Create import invoice",
                "parameters": [
                    {
                        "description": "Import invoice creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/importinvoicedto.CreateImportInvoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/importinvoicedto.CreateImportInvoiceResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/items": {
            "get": {
                "description": "API bao gồm cả lọc, phân trang và sắp xếp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get items",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 1,
                        "description": "Current page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "description": "Number record per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "name",
                        "description": "Sort column (vd: name)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "ASC",
                        "description": "Sort type: ASC hoặc DESC",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trường lọc (vd: email, full_name)",
                        "name": "searchBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Giá trị lọc (vd:abc@gmail.com, John Doe)",
                        "name": "searchValue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/itemdto.GetItemResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "post": {
                "description": "API thêm item mới",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Create new item",
                "parameters": [
                    {
                        "description": "Create item info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/itemdto.CreateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created item successfully",
                        "schema": {
                            "$ref": "#/definitions/itemdto.CreateItemResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/items/{itemID}": {
            "get": {
                "description": "API lấy thông tin item theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get item by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID item",
                        "name": "itemID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/itemdto.GetItemByIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "delete": {
                "description": "API xóa item theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Delete item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID item",
                        "name": "itemID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deleted item successfully",
                        "schema": {
                            "$ref": "#/definitions/itemdto.DeleteItemResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "patch": {
                "description": "API cập nhật item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Update item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID item",
                        "name": "itemID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update item info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/itemdto.UpdateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated item successfully",
                        "schema": {
                            "$ref": "#/definitions/itemdto.UpdateItemResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Đăng nhập người dùng với email và mật khẩu mạnh",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Dữ liệu đăng nhập",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authdto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authdto.LoginResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Đăng đăng xuất",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authdto.LogoutResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "description": "API bao gồm cả lọc, phân trang và sắp xếp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get posts",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 1,
                        "description": "Current page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "description": "Number record of page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "authorName, title, createdAt",
                        "description": "Sort column",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "ASC, DESC",
                        "description": "Sort type",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "1, 2, 3",
                        "description": "Pending:1, Rejected:2, Approved:3",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "1, 2, 3, 4",
                        "description": "GiveAwayOldItem:1, FoundItem:2, SeekLoseItem:3, Other:4",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trường lọc (vd: email, fullName)",
                        "name": "searchBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Giá trị lọc (vd:abc@gmail.com, John Doe)",
                        "name": "searchValue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/postdto.GetAdminPostResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "API tạo mới một post và trả về thông tin post + user + JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "description": "Post creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/postdto.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/postdto.CreatePostResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/posts/{postID}": {
            "get": {
                "description": "API lấy bài viết theo id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get detail post",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/postdto.GetDetailPostResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "patch": {
                "description": "API cập nhật bài viết kết hợp với patch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Update posts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update post info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/postdto.UpdatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated post successfully",
                        "schema": {
                            "$ref": "#/definitions/postdto.UpdatePostResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "API bao gồm cả lọc, phân trang và sắp xếp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get users",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 1,
                        "description": "Current page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "description": "Number record of page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "name",
                        "description": "Sort column (vd: fullName, email)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "ASC",
                        "description": "Sort type: ASC hoặc DESC",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trường lọc (vd: email, fullName)",
                        "name": "searchBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Giá trị lọc (vd:abc@gmail.com, John Doe)",
                        "name": "searchValue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userdto.GetUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "post": {
                "description": "API thêm người dùng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "Create user info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userdto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created user successfully",
                        "schema": {
                            "$ref": "#/definitions/userdto.CreateUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        },
        "/users/{userID}": {
            "get": {
                "description": "API get user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID user",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userdto.GetUserByIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "delete": {
                "description": "API delete user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID user",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userdto.DeleteUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            },
            "patch": {
                "description": "API cập nhật người dùng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID user",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update user info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userdto.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user successfully",
                        "schema": {
                            "$ref": "#/definitions/userdto.UpdateUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/enums.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "authdto.LoginRequest": {
            "type": "object",
            "required": [
                "device",
                "email",
                "password"
            ],
            "properties": {
                "device": {
                    "type": "string",
                    "enum": [
                        "mobile",
                        "web"
                    ],
                    "example": "web"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "description": "Password string ` + "`" + `json:\"password\" validate:\"required,password_strong\" example:\"Abc12345\"` + "`" + `",
                    "type": "string",
                    "example": "Abc12345"
                }
            }
        },
        "authdto.LoginResponse": {
            "type": "object",
            "properties": {
                "jwt": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/userdto.CommonUserDTO"
                }
            }
        },
        "authdto.LoginResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/authdto.LoginResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "authdto.LogoutResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "categorydto.CategoryDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "categorydto.GetCategoryResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/categorydto.CategoryDTO"
                    }
                }
            }
        },
        "categorydto.GetCategoryResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/categorydto.GetCategoryResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "enums.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "type": "string",
                    "example": "INVALID_QUERY_PARAM"
                },
                "message": {
                    "type": "string",
                    "example": "Name is require"
                }
            }
        },
        "enums.ItemClassify": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "ItemClassifyAll": "0 all",
                "ItemClassifyLoseItem": "2 đồ thất lạc",
                "ItemClassifyOlItem": "1 đồ cũ"
            },
            "x-enum-varnames": [
                "ItemClassifyAll",
                "ItemClassifyOlItem",
                "ItemClassifyLoseItem"
            ]
        },
        "enums.PostStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "PostStatusAll": "0 Người dùng đã gửi yêu cầu duyệt bài và đang chờ xử lý",
                "PostStatusApproved": "3 Admin duyệt",
                "PostStatusPending": "1 Người dùng đã gửi yêu cầu duyệt bài và đang chờ xử lý",
                "PostStatusRejected": "2 Admin đã từ chối"
            },
            "x-enum-varnames": [
                "PostStatusAll",
                "PostStatusPending",
                "PostStatusRejected",
                "PostStatusApproved"
            ]
        },
        "enums.PostType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-comments": {
                "PostTypeAll": "0 all",
                "PostTypeFoundItem": "2 nhặt được đồ",
                "PostTypeGiveAwayOldItem": "1 tặng đồ cũ",
                "PostTypeOther": "4 khác",
                "PostTypeSeekLoseItem": "3 tìm kiếm đồ"
            },
            "x-enum-varnames": [
                "PostTypeAll",
                "PostTypeGiveAwayOldItem",
                "PostTypeFoundItem",
                "PostTypeSeekLoseItem",
                "PostTypeOther"
            ]
        },
        "enums.UserStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "UserStatusActive": "2",
                "UserStatusAll": "0",
                "UserStatusInactive": "1",
                "UserStatusLocked": "3"
            },
            "x-enum-varnames": [
                "UserStatusAll",
                "UserStatusInactive",
                "UserStatusActive",
                "UserStatusLocked"
            ]
        },
        "importinvoicedto.CreateImportInvoiceRequest": {
            "type": "object",
            "required": [
                "classify",
                "itemImportInvoice",
                "senderID"
            ],
            "properties": {
                "classify": {
                    "enum": [
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.ItemClassify"
                        }
                    ],
                    "example": 1
                },
                "description": {
                    "type": "string"
                },
                "itemImportInvoice": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/importinvoicedto.CreateItemImportInvoiceRequest"
                    }
                },
                "senderID": {
                    "type": "integer"
                }
            }
        },
        "importinvoicedto.CreateImportInvoiceResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/warehousedto.ItemWarehouse"
                    }
                }
            }
        },
        "importinvoicedto.CreateImportInvoiceResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/importinvoicedto.CreateImportInvoiceResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "importinvoicedto.CreateItemImportInvoiceRequest": {
            "type": "object",
            "required": [
                "itemID",
                "quantity"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "itemID": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "itemdto.CreateItemRequest": {
            "type": "object",
            "required": [
                "categoryID",
                "name"
            ],
            "properties": {
                "categoryID": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "itemdto.CreateItemResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/itemdto.ItemDTO"
                }
            }
        },
        "itemdto.CreateItemResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/itemdto.CreateItemResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "itemdto.DeleteItemResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "itemdto.GetItemByIDResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/itemdto.ItemDTO"
                }
            }
        },
        "itemdto.GetItemByIDResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/itemdto.GetItemByIDResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "itemdto.GetItemResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/itemdto.ItemDTO"
                    }
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "itemdto.GetItemResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/itemdto.GetItemResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "itemdto.ItemDTO": {
            "type": "object",
            "properties": {
                "categoryID": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "itemdto.UpdateItemRequest": {
            "type": "object",
            "properties": {
                "categoryID": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "itemdto.UpdateItemResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/itemdto.ItemDTO"
                }
            }
        },
        "itemdto.UpdateItemResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/itemdto.UpdateItemResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "postdto.AdminPostDTO": {
            "type": "object",
            "properties": {
                "authorName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "postdto.CreatePostRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "strbase64",
                        " strbase64"
                    ]
                },
                "info": {
                    "type": "string"
                },
                "newItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/postdto.NewItemsPost"
                    }
                },
                "oldItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/postdto.OldItemsPost"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Tôi muốn tìm đồ thất lạc"
                },
                "type": {
                    "description": "Email       string         ` + "`" + `json:\"email\" example:\"john@gmail.com\"` + "`" + `\nFullName    string         ` + "`" + `json:\"fullName\" example:\"John Doe\"` + "`" + `\nPhoneNumber string         ` + "`" + `json:\"phoneNumber\" example:\"0123456789\"` + "`" + ` // true: anonymous, false: not anonymous",
                    "enum": [
                        1,
                        2,
                        3,
                        4
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.PostType"
                        }
                    ],
                    "example": 1
                }
            }
        },
        "postdto.CreatePostResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "postdto.DetailPostDTO": {
            "type": "object",
            "properties": {
                "authorID": {
                    "type": "integer"
                },
                "authorName": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "info": {
                    "type": "string"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/postdto.InterestDTO"
                    }
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/postdto.DetailPostItemDTO"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "postdto.DetailPostItemDTO": {
            "type": "object",
            "properties": {
                "categoryID": {
                    "type": "integer"
                },
                "categoryName": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "itemID": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "postdto.GetAdminPostResponse": {
            "type": "object",
            "properties": {
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/postdto.AdminPostDTO"
                    }
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "postdto.GetAdminPostResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/postdto.GetAdminPostResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "postdto.GetDetailPostResponse": {
            "type": "object",
            "properties": {
                "post": {
                    "$ref": "#/definitions/postdto.DetailPostDTO"
                }
            }
        },
        "postdto.GetDetailPostResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/postdto.GetDetailPostResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "postdto.InterestDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "postID": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "postdto.NewItemsPost": {
            "type": "object",
            "required": [
                "categoryID",
                "name"
            ],
            "properties": {
                "categoryID": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "postdto.OldItemsPost": {
            "type": "object",
            "required": [
                "itemID"
            ],
            "properties": {
                "image": {
                    "type": "string"
                },
                "itemID": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "postdto.UpdatePostRequest": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "strbase64",
                        " strbase64"
                    ]
                },
                "info": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        1,
                        2,
                        3
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.PostStatus"
                        }
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "Tôi muốn tìm đồ thất lạc"
                }
            }
        },
        "postdto.UpdatePostResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "userdto.CommonUserDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "goodPoint": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "major": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "roleID": {
                    "type": "integer"
                },
                "roleName": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "userdto.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "john@gmail.com"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "goodPoint": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "0123456789"
                },
                "status": {
                    "description": "0: inactive, 1: active, 2: banned",
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.UserStatus"
                        }
                    ],
                    "example": 1
                }
            }
        },
        "userdto.CreateUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/userdto.UserDTO"
                }
            }
        },
        "userdto.CreateUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/userdto.CreateUserResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "userdto.DeleteUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "userdto.GetUserByIDResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/userdto.UserDTO"
                }
            }
        },
        "userdto.GetUserByIDResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/userdto.GetUserByIDResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "userdto.GetUserResponse": {
            "type": "object",
            "properties": {
                "totalPage": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userdto.UserDTO"
                    }
                }
            }
        },
        "userdto.GetUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/userdto.GetUserResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "userdto.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "goodPoint": {
                    "type": "integer"
                },
                "major": {
                    "type": "string",
                    "example": "Information Technology"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "0123456789"
                },
                "status": {
                    "description": "0: inactive, 1: active, 2: banned",
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.UserStatus"
                        }
                    ],
                    "example": 1
                }
            }
        },
        "userdto.UpdateUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "userdto.UserDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "goodPoint": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "major": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "warehousedto.ItemWarehouse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "itemID": {
                    "type": "integer"
                },
                "itemName": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API DATN 2025",
	Description:      "Đây là tài liệu Swagger cho hệ thống.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
